use QUANLYCHUYENBAY3
go
------------------------------------View--------------------------------
--Xem tổng vé đã đặt
CREATE VIEW TONGVE
AS
	SELECT COUNT(VECHUYENBAY_DADAT.VECHUYENBAY_MaVeChuyenBay) AS TONG
	FROM VECHUYENBAY_DADAT

go
--xem doanh thu
CREATE VIEW DOANHTHU
AS
	SELECT SUM(DONGIA.GIA_USD) AS DOANHTHU
	FROM VECHUYENBAY JOIN VECHUYENBAY_DADAT ON VECHUYENBAY.MaVeChuyenBay = VECHUYENBAY_DADAT.VECHUYENBAY_MaVeChuyenBay 
		JOIN DONGIA ON DONGIA.MaDonGia_HangVe = VECHUYENBAY.DONGIA_MaDonGia
GO